apps/cart/urls.py
from django.conf.urls import url

from .views import CartAddView, CartInfoView, CartUpdateView, CartDeleteView

urlpatterns = [
    url(r'^add$', CartAddView.as_view(), name='add'),
    url(r'^update$', CartUpdateView.as_view(), name='update'),
    url(r'^delete$', CartDeleteView.as_view(), name='delete'),
    url(r'^$', CartInfoView.as_view(), name='show'),

]

apps/goods/urls.py
from django.conf.urls import url

from .views import IndexView, DetailView, ListView

app_name = '[goods]'
urlpatterns = [
    url(r'^index$', IndexView.as_view(), name='index'),
    url(r'^goods/(?P<goods_id>\d+)$', DetailView.as_view(), name='detail'),
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)', ListView.as_view(), name='list'),
]

apps/order/urls.py
from django.conf.urls import url

from .views import OrderPlaceView, OrderCommitView, OrderPayView, OrderCheckView


urlpatterns = [

    url(r'^place$', OrderPlaceView.as_view(), name='place'),    # 提交订单
    url(r'^commit$', OrderCommitView.as_view(), name='commit'),  # 创建订单
    url(r'^pay$', OrderPayView.as_view(), name='pay'),  # 支付
    url(r'^check$', OrderCheckView.as_view(), name='check'),  # 查询支付结果
]

apps/user/urls.py
from django.conf.urls import url

from .views import (
    RegisterView, ActiveView, LoginView,
    UserInfoView, UserOrderView, UserAddressView,
    LogoutView
)

app_name = '[user]'
urlpatterns = [
    # url(r'^register$', views.register, name='register'),
    # url(r'^register_handle$', views.register_handle, name='register_handle'), # 注册处理
    url(r'^register$', RegisterView.as_view(), name='register'),
    url(r'^active/(?P<token>.*)$', ActiveView.as_view(), name='active'),
    url(r'^login$', LoginView.as_view(), name='login'),
    url(r'^logout$', LogoutView.as_view(), name='logout'),
    url(r'^$', UserInfoView.as_view(), name='user'),  # 用户中心信息页
    url(r'^order/(?P<page>\d+)$', UserOrderView.as_view(), name='order'),
    url(r'^address$', UserAddressView.as_view(), name='address'),

]

cjh01/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),     # 富文本编辑器
    url(r'^user/', include('user.urls', namespace='user')),  # 用户
    url(r'^order/', include('order.urls', namespace='order')),  # 订单
    url(r'^cart/', include('cart.urls', namespace='cart')),     # 购物车
    url(r'^', include('goods.urls', namespace='goods')),    # 商品
    url(r'^search', include('haystack.urls')),  # 全文检索

]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django_redis import get_redis_connection

from goods.models import GoodsSKU


# /cart/add
class CartAddView(View):

    def post(self, request):
        # 购物车记录添加

        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        # 校验商品数量
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except Exception as e:
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理

        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # 获取sku_id的值,如果不存在,hget返回None
        cart_count = conn.hget(cart_key, sku_id)

        if cart_count:
            count += int(cart_count)  # 累加商品数量

        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '库存不足'})
        # 设置hash中sku_id对应的值
        # hset，如果数据存在，则更新数据，否则添加数据
        conn.hset(cart_key, sku_id, count)

        # 计算购物车的条目
        total_count = conn.hlen(cart_key)

        # 返回应答
        return JsonResponse({'res': 5, 'total_count': total_count, 'message': '数据添加成功'})


#  /cart/update  购物车记录更新
class CartUpdateView(View):

    def post(self, request):

        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        # 校验商品数量
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except Exception as e:
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理

        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '库存不足'})

        conn.hset(cart_key, sku_id, count)

        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        return JsonResponse({'res': 5, 'total_count': total_count, 'message': '数据更新成功'})


# /cart/delete 购物车删除记录
class CartDeleteView(View):

    def post(self, request):

        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接收数据
        sku_id = request.POST.get('sku_id')

        if not sku_id:
            return JsonResponse({'res': 1, 'errmsg': '无效sku_id'})

        # 验证商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品不存在'})

        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        conn.hdel(cart_key, sku_id)

        # 购物车商品数量
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        return JsonResponse({'res': 3, 'total_count': total_count, 'message': '删除成功'})


# /cart
class CartInfoView(View):

    def get(self, request):

        user = request.user
        if not user.is_authenticated():
            return redirect(reverse('user:login'))

        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        cart_dict = conn.hgetall(cart_key)

        skus = []
        total_count = 0
        total_price = 0
        # 遍历获取的商品信息
        for sku_id, count in cart_dict.items():
            # 根据商品id获取商品信息
            sku = GoodsSKU.objects.get(id=sku_id)
            # 计算商品的小计
            amount = sku.price * int(count)
            sku.amount = amount
            sku.count = count
            skus.append(sku)

            total_count += int(count)
            total_price += amount

        context = {
            'skus': skus,
            'total_count': total_count,
            'total_price': total_price
        }

        return render(request, 'cart.html', context)

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 标题 #}
	<title>{% block title %}{% endblock title%}</title>

	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {# 顶部引入文件块 #}
    {% block topfiles %}{% endblock topfiles%}
</head>
<body>
{# 网页顶部信息块 #}
{% block header_bar %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
{% endblock header_bar%}

{# 搜索 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form method="get" action="/search">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ curt_count }}</div>
		</div>
	</div>
{% endblock search_bar%}

{# 主体 #}
{% block body %}{% endblock body %}

{% block beihan %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{% endblock beihan %}

{# 网页底部html #}
{% block bottom %}{% endblock bottom %}

{# 底部引入文件 #}
{% block bottomfiles %}{% endblock bottomfiles%}
</body>
</html>

templates/base_detail_list.html
{% extends 'base.html' %}

{% block body %}
    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for type in types %}
					<li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    {# 详情页、列表页 #}
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

templates/base_user_center.html
{# 用户中心3页面 #}
{% extends 'base_no_cart.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-用户中心{% endblock title%}
{% block page_title %}用户中心{% endblock page_title %}

{% block body %}
    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" {% if page == 'user' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1 %}" {% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" {% if page == 'address' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>

        {% block right_content %}{% endblock right_content %}
    </div>
{% endblock body %}

templates/detail.html
{% extends 'base_detail_list.html' %}
{% load staticfiles %}

	{% block title %}天天生鲜-商品详情{% endblock title %}

{% block main_content %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ sku.type.name }}</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{ sku.image.url }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ sku.name }}</h3>
			<p>{{ sku.desc }}</p>
			<div class="prize_bar">

				<span class="show_pirze">¥<em>{{ sku.price }}</em></span>
				<span class="show_unit">单  位：{{ sku.unite }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div> 
			</div>
			<div class="total">总价：<em>16.80元</em></div>
			<div class="operate_btn">
                {% csrf_token %}
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" sku_id="{{ sku.id }}" class="add_cart" id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for new_sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' new_sku.id %}"><img src="{{ new_sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' new_sku.id %}">{{ new_sku.name }}</a></h4>
						<div class="prize">￥{{ new_sku.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ sku.goods.detail|safe }}</dd>
				</dl>
			</div>

            <div class="tab_content">
				<dl>
                    {% for order in sku_orders %}
					<dt>评论时间：{{ order.update_time }}&nbsp;&nbsp;用户名：{{ order.order.user.name }}</dt>
                    <dd>评论内容：</dd>
					{% endfor %}
				</dl>
			</div>

		</div>
	</div>
{% endblock main_content %}

{% block bottom %}
	<div class="add_jump"></div>
{% endblock bottom %}

{% block bottomfiles %}

	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">

        update_goods_amount();

        function update_goods_amount() {
            //获取商品的单价和数量
            price = $('.show_pirze').children('em').text();
            count = $('.num_show').val();

            //计算商品的总价
            price = parseFloat(price);
            count = parseInt(count);
            amount = price * count;

            //设置总价
            $('.total').children('em').text(amount.toFixed(2) + '元');
        }

        $('.minus').click(function () {
            // 获取原有的商品数目
            count = $('.num_show').val();
            count = parseInt(count) - 1;
            if(count <= 0){
                count = 1;
            }
            $('.num_show').val(count);

            update_goods_amount();

        });

       $('.add').click(function () {
            // 获取原有的商品数目
            count = $('.num_show').val();
            count = parseInt(count) + 1;
            if(count <= 0){
                count = 1;
            }
            $('.num_show').val(count);

            update_goods_amount();

        });

       $('.num_show').blur(function () {
           count = $(this).val();
           if(isNaN(count) || count.trim().length == 0 || parseInt(count) <= 0){
               count = 1
           }
           $(this).val(parseInt(count))
           update_goods_amount();
       });

		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;


		$('#add_cart').click(function(){

		    // 获取商品id和商品数量
            sku_id = $(this).attr('sku_id');
            count =  $('.num_show').val();
            csrf = $('input[name="csrfmiddlewaretoken"]').val();
            params = {'sku_id': sku_id, 'count': count, 'csrfmiddlewaretoken': csrf};

            // 发送ajax post请求， 访问/cart/add，传递参数sku_id、count
            $.post('/cart/add', params, function (data) {
                if ( data.res == 5 ){
                    //发送成功
                    $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'});
                    $(".add_jump").stop().animate({
				        'left': $to_y+7,
				        'top': $to_x+7},
				        "fast", function() {
                            $(".add_jump").fadeOut('fast',function(){
						        $('#show_count').html(data.total_count);
					        });

			            });
                }
                else{
                    //发送失败
                    alert(data.errmsg);
                }
            });


		})
	</script>
{% endblock bottomfiles%}
	

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

	{% block title %}天天生鲜-首页{% endblock %}
    {% block topfiles %}
        <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
    {% endblock %}

{% block body %}

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
			<li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for goods_banner in goods_banners %}
				<li><img src="{{ goods_banner.image.url }}" alt="幻灯片"></li>
                {% endfor %}

			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for goods_promotion in goods_promotions %}
			<a href="{{ goods_promotion.url }}"><img src="{{ goods_promotion.image.url }}"></a>
            {% endfor %}
		</div>
	</div>

    {% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>

			<div class="subtitle fl">
				<span>|</span>
                {% for banner in type.title_banners %}
				<a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a>
                {% endfor %}
			</div>

			<a href="{% url 'goods:list' type.id 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><a href="{% url 'goods:list' type.id 1 %}"><img src="{{ type.image.url }}"></a></div>
			<ul class="goods_list fl">

                {% for banner in type.image_banners%}
				<li>
					<h4><a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' banner.sku.id  %}"><img src="{{ banner.sku.image.url }}"></a>
					<div class="prize">¥ {{ banner.sku.price }}</div>
				</li>
                {% endfor %}

			</ul>
		</div>
	</div>
    {% endfor %}

{% endblock body %}

templates/list.html
{% extends 'base_detail_list.html' %}
	{% block tilte %}天天生鲜-商品列表{% endblock %}


{% block main_content %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ type.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for new_sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' new_sku.id %}"><img src="{{ new_sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' new_sku.id %}">{{ new_sku.name }}</a></h4>
						<div class="prize">￥{{ new_sku.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">

                {% for sku in skus_page %}
				<li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.price }}/{{ sku.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}

			</ul>

			<div class="pagenation">
                {% if skus_page.has_previous %}
				<a href="{% url 'goods:list' type.id skus_page.previous_page_number %}?sort={{ sort }}">上一页</a>
                {% endif %}

                {% for pindex in skus_page.paginator.page_range %}
                    {% if pindex == skus_page.number %}
				        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}" class="active">{{ pindex }}</a>
                    {% else %}
				        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}">{{ pindex }}</a>
                    {% endif %}

                {% endfor %}


                {% if skus_page.has_next %}
				<a href="{% url 'goods:list' type.id skus_page.next_page_number %}?sort={{ sort }}">下一页></a>
                {% endif %}
			</div>
		</div>
	</div>
{% endblock main_content %}


templates/place_order.html
{% extends 'base_no_cart.html' %}
{% load staticfiles %}
	{% block title %}天天生鲜-提交订单{% endblock title %}
    {% block page_title %}提交订单{% endblock page_title %}

{% block body %}
	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
            {% for addr in addrs %}
			<dd><input type="radio" name="addr_id" value="{{ addr.id }}" {% if addr.is_default %}checked=""{% endif %}>{{ addr.addr }} （{{ addr.receiver }} 收） {{ addr.phone }}</dd>
            {% endfor %}
		</dl>
		<a href="{% url 'user:address' %}" class="edit_site">编辑收货地址</a>

	</div>
	
	<h3 class="common_title">支付方式</h3>	
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" value="1" checked>
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style" value="2">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style" value="3">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style" value="4">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>
	
	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>		
		</ul>

        {% for sku in skus %}
		<ul class="goods_list_td clearfix">
			<li class="col01">{{ forloop.counter }}</li>
			<li class="col02"><img src="{{ sku.image.url }}"></li>
			<li class="col03">{{ sku.name }}</li>
			<li class="col04">{{ sku.unite }}</li>
			<li class="col05">{{ sku.price }}元</li>
			<li class="col06">{{ sku.count }}</li>
			<li class="col07">{{ sku.amount }}元</li>
		</ul>
        {% endfor %}

	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>{{ total_count }}</em>件商品，总金额<b>{{ total_price }}元</b></div>
			<div class="transit">运费：<b>{{ transit_price }}元</b></div>
			<div class="total_pay">实付款：<b>{{ total_pay }}元</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
        {% csrf_token %}
		<a href="javascript:;" sku_ids={{ sku_ids }} id="order_btn">提交订单</a>
	</div>	

{% endblock body %}

{% block bottom %}
	<div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>
		
		<div class="mask"></div>
	</div>
{% endblock bottom %}

{% block bottomfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">
		$('#order_btn').click(function() {

		    // 选取用户选择的地址id，支付方式，要购买商品的id字符串
            addr_id = $('input[name="addr_id"]:checked').val();
            pay_method = $('input[name="pay_style"]:checked').val();
            sku_ids = $(this).attr('sku_ids');
            csrf = $('input[name="csrfmiddlewaretoken"]').val();

            params = {'addr_id': addr_id, 'pay_method': pay_method, 'sku_ids': sku_ids, 'csrfmiddlewaretoken': csrf};

            // 发起ajax post请求，访问/order/commit , 传递参数addr_id、pay_method、sku_ids, csrfmiddlewaretoken
            $.post('/order/commit',params, function (data) {
                if (data.res == 5){
                    // 创建成功
                    localStorage.setItem('order_finish',2);

			            $('.popup_con').fadeIn('fast', function() {

                        setTimeout(function(){
                            $('.popup_con').fadeOut('fast',function(){
                                window.location.href = '{% url 'user:order' 1 %}';
                            });
                        },3000)

			            });
                }
                else{
                    //失败
                    alert('创建失败')
                }

            });


		});
	</script>
{% endblock bottomfiles %}

templates/user_center_info.html
{% extends 'base_user_center.html' %}

    {% block right_content %}
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				    <h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user.username }}</li>
                            {% if address %}
							<li><span>联系方式：</span>{{ address.phone }}</li>
							<li><span>联系地址：</span>{{ address.addr }}</li>
                            {% else %}
                            <li><span>联系方式：</span>无默认</li>
							<li><span>联系地址：</span>无默认</li>
                            {% endif %}
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                        {% for good in goods_li %}
                        <li>
                            <a href="{% url 'goods:detail' good.id %}"><img src="{{ good.image.url }}"></a>
                            <h4><a href="{% url 'goods:detail' good.id %}.html">{{ good.name }}</a></h4>
                            <div class="operate">
                                <span class="prize">￥{{ good.price }}</span>
                                <span class="unit">{{ good.price }}/{{ good.unite }}</span>
                                <a href="#" class="add_goods" title="加入购物车"></a>
                            </div>
                        </li>
                        {% empty %}
                            没有浏览记录
                        {% endfor %}
			    </ul>
		    </div>
		</div>
    {% endblock right_content %}
